name: Build Flutter iOS App

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the master branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Build iOS Release
        run: |
          flutter build ios --release

      - name: Upload build artifact (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: ios-release-build
          path: build/ios/iphoneos/*.ipa  # This will upload the .ipa file
